#!/usr/bin/env bash
exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging
set -eu +x -o pipefail

DESTINATION=$1
payload=$DESTINATION/data
cat > "$payload" <&0

PROJECT_ID=$(jq -r '.source.project_id' < "$payload")
TOKEN=$(jq -r '.source.token' < "$payload")
LABEL=$(jq -r '.source.label' < "$payload")
STORIES=$(jq -r '.version' < "$payload")

echo "VERSION CONTENT:"
echo $STORIES

echo "{ \"version\": { \"ref\": \"payload\" } }" >&3
