platform: linux
image_resource:
  type: docker-image
  source:
    repository: jandubois/opensusefs2
inputs:
  - name: binary-builder
  - name: buildpacks-ci
params:
  RUBYGEM_MIRROR:
run:
  path: buildpacks-ci/tasks/run-binary-builder-unit-specs/run.sh
